// styles/MainSyncModalStyles.ts - Main modal for sync steps
import { StyleSheet } from 'react-native';
import { COLORS } from '../app/styles';

export const MainSyncModalStyles = StyleSheet.create({
  modalContainer: {
    backgroundColor: '#111',
    borderRadius: 10,
    padding: 15,
    borderWidth: 1,
    borderColor: COLORS.primary,
    flex: 1,
    marginVertical: 20,
    marginHorizontal: 15,
    maxHeight: '95%',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 20,
  },
  stepTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 10,
    textAlign: 'center',
  },
  emptyMessage: {
    color: COLORS.primary,
    textAlign: 'center',
    padding: 20,
    fontSize: 14,
  },
  
  // Table selection styles
  tableButton: {
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    padding: 15,
    marginVertical: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tableInfo: {
    flex: 1,
  },
  tableNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  tableName: {
    fontSize: 14,
    color: 'rgba(255, 215, 0, 0.8)',
    marginTop: 2,
  },
  tablePeople: {
    fontSize: 12,
    color: 'rgba(255, 215, 0, 0.6)',
    marginTop: 4,
  },
  
  // Person selection styles
  personButton: {
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    padding: 15,
    marginVertical: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  personInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  personAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 15,
  },
  personDetails: {
    flex: 1,
  },
  personName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  personTotal: {
    fontSize: 14,
    color: 'rgba(255, 215, 0, 0.8)',
    marginTop: 2,
  },
  personOrders: {
    fontSize: 12,
    color: 'rgba(255, 215, 0, 0.6)',
    marginTop: 2,
  },
  
  // Product selection styles
  productButton: {
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    padding: 15,
    marginVertical: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  selectedProduct: {
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    borderColor: COLORS.primary,
    borderWidth: 2,
  },
  productInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  productQuantity: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginRight: 10,
    minWidth: 30,
  },
  productName: {
    fontSize: 14,
    color: COLORS.primary,
    flex: 1,
  },
  productPrice: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginLeft: 10,
  },
  
  // Total container
  totalContainer: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    padding: 15,
    marginVertical: 10,
    alignItems: 'center',
  },
  totalText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
  },
  
  // Button styles
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
    gap: 10,
    paddingBottom: 10,
    paddingHorizontal: 2,
  },
  backButton: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    minHeight: 48,
  },
  backButtonText: {
    color: COLORS.primary,
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 8,
  },
  generateButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    minHeight: 48,
  },
  generateButtonText: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 8,
  },
  disabledButton: {
    opacity: 0.5,
  },
  receiveButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    minHeight: 48,
  },
  receiveButtonText: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 8,
  },
  cancelButton: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  cancelButtonText: {
    color: COLORS.primary,
    fontWeight: 'bold',
    fontSize: 14,
  },
  
  // QR Code display styles
  qrModalContainer: {
    backgroundColor: '#111',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    maxHeight: '95%',
    minHeight: 500,
    borderWidth: 1,
    borderColor: COLORS.primary,
    justifyContent: 'space-between',
  },
  qrTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 10,
  },
  qrSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 215, 0, 0.8)',
    textAlign: 'center',
    marginBottom: 20,
  },
  qrContainer: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  qrInfoContainer: {
    alignItems: 'center',
    marginVertical: 15,
  },
  qrInfoText: {
    color: COLORS.primary,
    fontSize: 14,
    marginVertical: 3,
    textAlign: 'center',
  },
  qrButtonsContainer: {
    flexDirection: 'column',
    width: '100%',
    gap: 10,
    paddingHorizontal: 2,
  },
  confirmRemovalButton: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  confirmRemovalButtonText: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 8,
  },
  backToProductsButton: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  backToProductsButtonText: {
    color: COLORS.primary,
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 8,
  },
  
  // Receive Data Modal - Responsive Layout
  receiveModalContent: {
    alignItems: 'center',
    paddingVertical: 20,
    flex: 1,
    justifyContent: 'space-between',
  },
  receiveQRIcon: {
    marginBottom: 15,
  },
  receiveTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 15,
  },
  receiveDescription: {
    fontSize: 14,
    color: 'rgba(255, 215, 0, 0.8)',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  receiveInfoBox: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 10,
    padding: 15,
    marginBottom: 20,
    width: '100%',
    flex: 1,
    minHeight: 120,
  },
  receiveInfoBoxTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 10,
  },
  receiveInfoText: {
    fontSize: 14,
    color: 'rgba(255, 215, 0, 0.8)',
    lineHeight: 22,
  },
  receiveButtonsContainer: {
    width: '100%',
    marginTop: 'auto',
  },
  scanButton: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    borderRadius: 10,
    marginBottom: 10,
    width: '100%',
  },
  scanButtonText: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 8,
  },
  voltarButton: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  voltarButtonText: {
    color: COLORS.primary,
    fontWeight: 'bold',
    fontSize: 14,
  },
  
  // Received data styles
  receivedDataContainer: {
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderRadius: 8,
    padding: 15,
    marginVertical: 10,
    maxHeight: '70%',
    flex: 1,
  },
  receivedDataLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginTop: 10,
  },
  receivedDataValue: {
    fontSize: 13,
    color: 'rgba(255, 215, 0, 0.9)',
    marginTop: 2,
    marginBottom: 5,
  },
  receivedProductItem: {
    fontSize: 12,
    color: 'rgba(255, 215, 0, 0.8)',
    marginLeft: 10,
    marginVertical: 2,
  },
  receivedDataTotal: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginTop: 10,
    textAlign: 'center',
  },
  
  // Import confirmation styles - COMPLETE REWRITE
  importModalContent: {
    flex: 1,
  },
  importScrollContent: {
    paddingBottom: 20,
    paddingRight: 10, // Add padding for custom scroll indicator
  },
  // Custom scroll indicator container
  scrollIndicatorContainer: {
    position: 'absolute',
    right: 2,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    borderRadius: 2,
  },
  scrollIndicatorThumb: {
    backgroundColor: COLORS.primary,
    borderRadius: 2,
    width: 4,
  },
  importConfirmContainer: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  importIconContainer: {
    marginBottom: 20,
  },
  importTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 10,
    textAlign: 'center',
  },
  importSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 215, 0, 0.8)',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
    paddingHorizontal: 10,
  },
  importDetailsContainer: {
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderRadius: 8,
    padding: 15,
    marginBottom: 15,
    width: '100%',
  },
  importDetailRow: {
    marginBottom: 12,
  },
  importDetailLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 3,
  },
  importDetailValue: {
    fontSize: 13,
    color: 'rgba(255, 215, 0, 0.9)',
    lineHeight: 16,
  },
  importProductsSection: {
    marginTop: 12,
    marginBottom: 12,
  },
  importProductsTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 6,
  },
  importProductItem: {
    fontSize: 12,
    color: 'rgba(255, 215, 0, 0.8)',
    marginLeft: 8,
    marginVertical: 2,
    lineHeight: 14,
  },
  importTotalSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 215, 0, 0.3)',
  },
  importTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  importTotalLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  importTotalValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  importWarningContainer: {
    paddingHorizontal: 15,
    marginBottom: 15,
  },
  importWarning: {
    fontSize: 11,
    color: '#FFA500',
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: 14,
  },
  importButtonsContainer: {
    flexDirection: 'column',
    gap: 10,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 215, 0, 0.2)',
  },
  importConfirmButton: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 8,
    minHeight: 48,
    width: '100%',
  },
  importConfirmButtonText: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 12,
    marginLeft: 8,
    textAlign: 'center',
  },
});