// styles/SelectiveSyncModalStyles.ts
import { StyleSheet } from 'react-native';
import { COLORS } from '../app/styles';

export const SelectiveSyncModalStyles = StyleSheet.create({
  modalContainer: {
    backgroundColor: COLORS.card,
    borderRadius: 15,
    padding: 20,
    height: '95%',
    width: '95%',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 15,
  },
  stepTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.primary,
    marginBottom: 20,
    textAlign: 'center',
  },
  tableButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.3)',
  },
  tableInfo: {
    flex: 1,
  },
  tableNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  tableName: {
    fontSize: 14,
    color: COLORS.primary,
    opacity: 0.8,
    marginTop: 2,
  },
  tablePeople: {
    fontSize: 12,
    color: COLORS.primary,
    opacity: 0.7,
    marginTop: 4,
  },
  personButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.3)',
  },
  personInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  personAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 15,
  },
  personDetails: {
    flex: 1,
  },
  personName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  personTotal: {
    fontSize: 14,
    color: COLORS.primary,
    opacity: 0.8,
    marginTop: 2,
  },
  personOrders: {
    fontSize: 12,
    color: COLORS.primary,
    opacity: 0.7,
    marginTop: 2,
  },
  productButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.3)',
  },
  selectedProduct: {
    backgroundColor: 'rgba(255, 215, 0, 0.3)',
    borderColor: COLORS.primary,
  },
  productInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  productQuantity: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginRight: 10,
  },
  productName: {
    fontSize: 16,
    color: COLORS.primary,
    flex: 1,
    marginRight: 10,
  },
  productPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  totalContainer: {
    backgroundColor: COLORS.primary,
    padding: 15,
    borderRadius: 10,
    marginVertical: 10,
  },
  totalText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
    textAlign: 'center',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    gap: 10,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: COLORS.primary,
    padding: 15,
    borderRadius: 10,
    flex: 1,
    justifyContent: 'center',
  },
  backButtonText: {
    color: COLORS.primary,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  generateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    padding: 15,
    borderRadius: 10,
    flex: 1,
    justifyContent: 'center',
  },
  generateButtonText: {
    color: 'black',
    fontWeight: 'bold',
    marginLeft: 8,
  },
  receiveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: COLORS.primary,
    padding: 15,
    borderRadius: 10,
    flex: 1,
    justifyContent: 'center',
  },
  receiveButtonText: {
    color: COLORS.primary,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  cancelButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: COLORS.primary,
    padding: 15,
    borderRadius: 10,
    flex: 1,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: COLORS.primary,
    fontWeight: 'bold',
  },
  disabledButton: {
    opacity: 0.5,
  },
  qrModalContainer: {
    backgroundColor: COLORS.card,
    borderRadius: 15,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.primary,
    height: '95%',
    width: '95%',
    alignSelf: 'center',
  },
  qrTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 10,
    textAlign: 'center',
  },
  qrSubtitle: {
    fontSize: 16,
    color: COLORS.primary,
    marginBottom: 20,
    opacity: 0.8,
    textAlign: 'center',
  },
  qrContainer: {
    backgroundColor: 'white',
    padding: 15,
    borderRadius: 15,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  qrInfoContainer: {
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    width: '100%',
  },
  qrInfoText: {
    color: COLORS.primary,
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 5,
  },
  qrButtonsContainer: {
    width: '100%',
    flexDirection: 'column',
    gap: 10,
  },
  confirmRemovalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4CAF50',
    padding: 15,
    borderRadius: 10,
    justifyContent: 'center',
  },
  confirmRemovalButtonText: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 8,
  },
  backToProductsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: COLORS.primary,
    padding: 15,
    borderRadius: 10,
    justifyContent: 'center',
  },
  backToProductsButtonText: {
    color: COLORS.primary,
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 8,
  },
  confirmOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  confirmModal: {
    backgroundColor: COLORS.card,
    borderRadius: 15,
    padding: 25,
    margin: 20,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFA500',
  },
  confirmTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginTop: 15,
    marginBottom: 15,
    textAlign: 'center',
  },
  confirmMessage: {
    fontSize: 16,
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 22,
  },
  confirmInstruction: {
    fontSize: 14,
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 25,
    fontStyle: 'italic',
    opacity: 0.8,
  },
  confirmButtons: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
  },
  cancelConfirmButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: COLORS.primary,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  cancelConfirmButtonText: {
    color: COLORS.primary,
    fontWeight: 'bold',
  },
  proceedConfirmButton: {
    flex: 1,
    backgroundColor: '#FF5722',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  proceedConfirmButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  emptyMessage: {
    color: COLORS.primary,
    textAlign: 'center',
    padding: 20,
    fontSize: 16,
  },
  receiveContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  receiveTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginTop: 20,
    textAlign: 'center',
  },
  receiveText: {
    fontSize: 14,
    color: COLORS.primary,
    textAlign: 'center',
    marginTop: 15,
    opacity: 0.8,
    paddingHorizontal: 20,
  },
});