// styles/SyncMenuModalStyles.ts
import { StyleSheet } from 'react-native';
import { COLORS } from '../app/styles';

export const SyncMenuModalStyles = StyleSheet.create({
  modalContainer: {
    backgroundColor: COLORS.card,
    borderRadius: 10,
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 20,
  },
  modalInfoText: {
    fontSize: 14,
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 20,
    opacity: 0.8,
  },
  previewContainer: {
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    padding: 15,
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.3)',
  },
  previewTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 10,
  },
  previewItem: {
    fontSize: 14,
    color: COLORS.primary,
    marginBottom: 5,
  },
  previewNote: {
    fontSize: 12,
    color: COLORS.primary,
    marginTop: 10,
    fontStyle: 'italic',
    opacity: 0.7,
  },
  optionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 30,
  },
  optionButton: {
    alignItems: 'center',
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 10,
    width: '45%',
    backgroundColor: 'transparent',
  },
  sendOptionButton: {
    alignItems: 'center',
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 10,
    width: '45%',
    backgroundColor: 'transparent',
  },
  receiveOptionButton: {
    alignItems: 'center',
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 10,
    width: '45%',
    backgroundColor: COLORS.primary,
  },
  optionText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginTop: 10,
  },
  optionDescription: {
    fontSize: 12,
    color: COLORS.primary,
    textAlign: 'center',
    marginTop: 5,
    opacity: 0.8,
  },
  qrModalContainer: {
    backgroundColor: '#111111',
    borderRadius: 15,
    padding: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.primary,
    maxHeight: '95%',
    width: '95%',
    alignSelf: 'center',
  },
  qrTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 10,
    textAlign: 'center',
  },
  qrSubtitle: {
    fontSize: 16,
    color: COLORS.primary,
    marginBottom: 20,
    opacity: 0.8,
    textAlign: 'center',
  },
  qrContainer: {
    backgroundColor: 'white',
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  infoGrid: {
    width: '100%',
    marginBottom: 20,
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 15,
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderRadius: 8,
    marginBottom: 10,
  },
  infoText: {
    color: COLORS.primary,
    fontSize: 14,
    marginLeft: 15,
    fontWeight: '500',
  },
  buttonContainer: {
    width: '100%',
    gap: 10,
  },
  confirmButton: {
    backgroundColor: COLORS.primary,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    width: '100%',
  },
  confirmButtonText: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 16,
  },
  closeButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: COLORS.primary,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    width: '100%',
  },
  closeButtonText: {
    color: COLORS.primary,
    fontWeight: 'bold',
    fontSize: 16,
  },
  
  // Received data styles
  receivedDataContainer: {
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    padding: 15,
    borderRadius: 10,
    marginTop: 15,
    marginBottom: 15,
    maxHeight: 400,
  },
  receivedDataLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginTop: 10,
    marginBottom: 5,
  },
  receivedDataValue: {
    fontSize: 14,
    color: COLORS.primary,
    marginBottom: 5,
    opacity: 0.9,
  },
  receivedProductItem: {
    fontSize: 13,
    color: COLORS.primary,
    marginLeft: 10,
    marginBottom: 3,
    opacity: 0.8,
  },
  receivedDataTotal: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginTop: 10,
    textAlign: 'center',
  },
  receivedDataButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  scanAgainButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    padding: 12,
    borderRadius: 8,
  },
  scanAgainButtonText: {
    color: 'black',
    fontWeight: 'bold',
    marginLeft: 5,
  },
  closeReceiveButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.primary,
    backgroundColor: 'transparent',
    alignItems: 'center',
  },
  closeReceiveButtonText: {
    color: COLORS.primary,
    fontWeight: 'bold',
  },
});